In [45]:
import pandas as pd
import pickle as pk
import csv

In [3]:
obj = pd.read_pickle(r'/Users/stephanie.rosales/Documents/omics_projects/POR_16S/CoralPersistence/metadata/TCM-datasets.pickle')

In [69]:
path="/Users/stephanie.rosales/Documents/omics_projects/POR_16S/CoralPersistence/metadata/"

In [8]:
obj.keys()

dict_keys(['CF', 'GR', 'ND', 'PI'])

In [83]:
pd.DataFrame.from_dict(obj)

,CF,GR,ND,PI
Top,Speed (cm/s) Bearing (de...,Speed (cm/s) Bearing (de...,Speed (cm/s) Bearing (de...,Speed (cm/s) Bearing (de...
Bottom,Speed (cm/s) Bearing (de...,Speed (cm/s) Bearing (de...,Speed (cm/s) Bearing (de...,Speed (cm/s) Bearing (de...
Sand,NaN,NaN,Speed (cm/s) Bearing (de...,NaN

In [105]:
CF_top=pd.DataFrame.from_dict(obj['CF']["Top"])
CF_top

,Speed (cm/s),Bearing (degrees),Velocity-N (cm/s),Velocity-E (cm/s),Temperature (C)
ISO 8601 Time,,,,,
2018-10-22 05:00:00,36.25,156.41,-33.22,14.51,23.4131
2018-10-22 05:05:00,36.25,156.39,-33.22,14.52,23.2627
2018-10-22 05:10:00,36.25,156.37,-33.21,14.53,23.4311
2018-10-22 05:15:00,36.25,156.31,-33.20,14.57,23.3317
2018-10-22 05:20:00,36.25,156.41,-33.22,14.51,23.0338
...,...,...,...,...,...
2019-05-24 17:15:00,64.70,238.83,-33.49,-55.36,30.4052
2019-05-24 17:20:00,64.70,238.40,-33.90,-55.11,30.4329
2019-05-24 17:25:00,64.70,238.42,-33.88,-55.12,30.4518
2019-05-24 17:30:00,64.70,238.19,-34.10,-54.98,30.4503
2019-05-24 17:35:00,43.93,29.60,38.20,21.70,30.4795

In [112]:
CF_top['reef'] = 'cf'
CF_top['place'] = 'top'
CF_top.columns = CF_top.columns.str.replace(' ', '') 
print(CF_top)

                     Speed(cm/s)  Bearing(degrees)  Velocity-N(cm/s)  \
ISO 8601 Time
2018-10-22 05:00:00        36.25            156.41            -33.22
2018-10-22 05:05:00        36.25            156.39            -33.22
2018-10-22 05:10:00        36.25            156.37            -33.21
2018-10-22 05:15:00        36.25            156.31            -33.20
2018-10-22 05:20:00        36.25            156.41            -33.22
...                          ...               ...               ...
2019-05-24 17:15:00        64.70            238.83            -33.49
2019-05-24 17:20:00        64.70            238.40            -33.90
2019-05-24 17:25:00        64.70            238.42            -33.88
2019-05-24 17:30:00        64.70            238.19            -34.10
2019-05-24 17:35:00        43.93             29.60             38.20

                     Velocity-E(cm/s)  Temperature(C) reef place
ISO 8601 Time
2018-10-22 05:00:00             14.51         23.4131   cf   top
2018-10-22 05:05:00             14.52         23.2627   cf   top
2018-10-22 05:10:00             14.53         23.4311   cf   top
2018-10-22 05:15:00             14.57         23.3317   cf   top
2018-10-22 05:20:00             14.51         23.0338   cf   top
...                               ...             ...  ...   ...
2019-05-24 17:15:00            -55.36         30.4052   cf   top
2019-05-24 17:20:00            -55.11         30.4329   cf   top
2019-05-24 17:25:00            -55.12         30.4518   cf   top
2019-05-24 17:30:00            -54.98         30.4503   cf   top
2019-05-24 17:35:00             21.70         30.4795   cf   top

[61784 rows x 7 columns]

In [120]:
CF_bottom=pd.DataFrame.from_dict(obj['CF']["Bottom"])
CF_bottom['reef'] = 'cf'
CF_bottom['place'] = 'bottom'
CF_bottom.columns = CF_top.columns.str.replace(' ', '') 
CF_bottom

,Speed(cm/s),Bearing(degrees),Velocity-N(cm/s),Velocity-E(cm/s),Temperature(C),reef,place
ISO 8601 Time,,,,,,,
2019-09-04 13:52:43,48.23,243.69,-21.37,-43.23,1453.0000,cf,bottom
2019-09-04 13:57:43,62.50,266.04,-4.31,-62.35,24.9625,cf,bottom
2019-09-04 14:02:43,69.60,266.76,-3.93,-69.49,24.8025,cf,bottom
2019-09-04 14:07:43,69.50,266.83,-3.84,-69.39,23.6328,cf,bottom
2019-09-04 14:12:43,69.50,267.23,-3.36,-69.42,23.2324,cf,bottom
...,...,...,...,...,...,...,...
2020-03-01 17:06:18,68.90,132.72,-46.74,50.62,22.6041,cf,bottom
2020-03-01 17:11:18,68.90,132.78,-46.79,50.57,22.5573,cf,bottom
2020-03-01 17:16:18,68.90,132.69,-46.72,50.64,22.6426,cf,bottom
2020-03-01 17:21:18,68.90,132.92,-46.92,50.46,22.5615,cf,bottom
2020-03-01 17:26:18,32.26,327.20,27.12,-17.47,22.5394,cf,bottom

In [130]:
ND_bottom=pd.DataFrame.from_dict(obj['ND']["Bottom"])
ND_bottom['reef'] = 'ndr'
ND_bottom['place'] = 'bottom'
ND_bottom.columns = ND_bottom.columns.str.replace(' ', '') 

ND_Top=pd.DataFrame.from_dict(obj['ND']["Top"])
ND_Top['reef'] = 'ndr'
ND_Top['place'] = 'top'
ND_Top.columns = ND_Top.columns.str.replace(' ', '') 

ND_sand=pd.DataFrame.from_dict(obj['ND']["Sand"])
ND_sand['reef'] = 'ndr'
ND_sand['place'] = 'sand'
ND_sand.columns = ND_sand.columns.str.replace(' ', '')

In [132]:
PR_Top=pd.DataFrame.from_dict(obj['PI']["Top"])
PR_Top['reef'] = 'pr'
PR_Top['place'] = 'top'
PR_Top.columns = PR_Top.columns.str.replace(' ', '') 

PR_bottom=pd.DataFrame.from_dict(obj['PI']["Bottom"])
PR_bottom['reef'] = 'pr'
PR_bottom['place'] = 'bottom'
PR_bottom.columns = PR_bottom.columns.str.replace(' ', '')

In [133]:
combo_df=pd.concat([CF_top, CF_bottom, ND_bottom, ND_Top, ND_sand, PR_Top, PR_bottom])

In [135]:
combo_df.to_csv('/Users/stephanie.rosales/Documents/omics_projects/POR_16S/CoralPersistence/metadata/POR_TCM_combo.csv')