In [1]:
library(ggplot2)
library(microbiome)
library(phyloseq)
library("tidyverse")
library("dplyr")
library("randomForestSRC")

Loading required package: phyloseq


microbiome R package (microbiome.github.com)



 Copyright (C) 2011-2022 Leo Lahti,
    Sudarshan Shetty et al. <microbiome.github.io>



Attaching package: ‘microbiome’


The following object is masked from ‘package:ggplot2’:

    alpha


The following object is masked from ‘package:base’:

    transform


── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ microbiome::alpha() masks ggplot2::alpha()
✖ dplyr::filter()     masks stats::filter()
✖ dplyr::lag()        masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

 randomForestSRC 3.2.2

 Type rfsrc.news() to see new features, changes, and bug fixes.




Attaching package: ‘randomForestSRC’


The following object is masked from ‘package:purrr’:

    partial

In [2]:
load("/Users/stephanie.rosales/Documents/omics_projects/POR_16S/CoralPersistence/data/POR_counts_4_analysis.RData")
load("/Users/stephanie.rosales/Documents/omics_projects/POR_16S/CoralPersistence/data/POR_taxo_4_analysis.RData")

In [4]:
taxo_mat <- POR_taxo_4_analysis %>%
  rownames_to_column %>%
  filter(rowname != 'ASV_2') %>%
column_to_rownames("rowname")  %>%
  mutate(domain = ifelse(row.names(.) == "ASV_5", "ASV_5:core", domain)) %>%
  mutate(phylum = ifelse(row.names(.) == "ASV_5", "ASV_5:core", phylum)) %>%
  mutate(class = ifelse(row.names(.) == "ASV_5", "ASV_5:core", class)) %>%
   mutate(order = ifelse(row.names(.) == "ASV_5", "ASV_5:core", order)) %>%
  mutate(family = ifelse(row.names(.) == "ASV_5", "ASV_5:core", family)) %>%
mutate(genus = ifelse(row.names(.) == "ASV_5", "ASV_5:core", genus)) %>%
mutate(species = ifelse(row.names(.) == "ASV_5", "ASV_5:core", species)) %>%
 mutate(domain = ifelse(row.names(.) == "ASV_6", "ASV_6:core", domain)) %>%
  mutate(phylum = ifelse(row.names(.) == "ASV_6", "ASV_6:core", phylum)) %>%
  mutate(class = ifelse(row.names(.) == "ASV_6", "ASV_6:core", class)) %>%
   mutate(order = ifelse(row.names(.) == "ASV_6", "ASV_6:core", order)) %>%
  mutate(family = ifelse(row.names(.) == "ASV_6", "ASV_6:core", family)) %>%
mutate(genus = ifelse(row.names(.) == "ASV_6", "ASV_6:core", genus)) %>%
mutate(species = ifelse(row.names(.) == "ASV_6", "ASV_6:core", species)) %>%
mutate(class = ifelse(row.names(.) == "ASV_7", "SAR324:core", class)) %>%
   mutate(order = ifelse(row.names(.) == "ASV_7", "SAR324:core", order)) %>%
  mutate(family = ifelse(row.names(.) == "ASV_7", "SAR324:core", family)) %>%
mutate(genus = ifelse(row.names(.) == "ASV_7", "SAR324:core", genus)) %>%
mutate(species = ifelse(row.names(.) == "ASV_7", "SAR324:core", species)) %>%
mutate(genus = ifelse(row.names(.) == "ASV_23", "Cyanobiaceae:core", genus)) %>%
mutate(species = ifelse(row.names(.) == "ASV_23", "Cyanobiaceae:core", species))

In [10]:
sapply(as.data.frame(tax_table(ps_fill)), function(x) sum(is.na(x)))

 domain  phylum   class   order  family   genus species
     27      37      43      67      95     214     372

In [8]:

meta = read.csv ("/Users/stephanie.rosales/Documents/omics_projects/POR_16S/CoralPersistence/metadata/POR_combo_meta.csv",
row.names=1, header = T)%>%
  mutate(
    Month = factor(Month, levels = month.name)
  ) %>%
  arrange(Month) %>%
arrange(collection_date)

ASV <- otu_table(as.matrix(POR_counts_4_analysis), 
                 taxa_are_rows = T)
TAX <- tax_table(as.matrix(taxo_mat))
SAMP <- sample_data(meta)

ps <- phyloseq(ASV, TAX, SAMP)
ps

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 27533 taxa and 363 samples ]
sample_data() Sample Data:       [ 363 samples by 54 sample variables ]
tax_table()   Taxonomy Table:    [ 27533 taxa by 7 taxonomic ranks ]

In [9]:
ps_fill = filter_taxa(ps, function(x) sum(x > 5) > (0.1*length(x)), TRUE)
ps_fill

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 376 taxa and 363 samples ]
sample_data() Sample Data:       [ 363 samples by 54 sample variables ]
tax_table()   Taxonomy Table:    [ 376 taxa by 7 taxonomic ranks ]

In [31]:
predictors <- t(otu_table(ps_fill))
dim(predictors)
# Make one column for our outcome/response variable 

response <- as.factor(sample_data(ps_fill)$NO2.uM.)

# Combine them into 1 data frame
rf.data <- data.frame(response, predictors)
head(rf.data, n=2)


set.seed(2)
NO2.classify <- rfsrc(response~., data = rf.data, ntree = 400,
                     importance="permute", csv.num=TRUE)
NO2.classify

cbind(as.data.frame(NO2.classify$importance), as.data.frame(tax_table(ps_fill))) %>%
arrange(-all) %>%
head()

[1] 363 376

               response ASV_479 ASV_365 ASV_535 ASV_338 ASV_930 ASV_548 ASV_374
bagnumber-1009 0.032    0       0       14      0        0      0        0
bagnumber-1010 0.032    0       7       21      0       10      0       12
               ASV_621 ASV_925 ⋯ ASV_1185 ASV_1313 ASV_1321 ASV_1399 ASV_1429
bagnumber-1009 0       0       ⋯ 6        0         0       0        0
bagnumber-1010 0       0       ⋯ 8        0        12       0        0
               ASV_1511 ASV_1546 ASV_1827 ASV_1966 ASV_2147
bagnumber-1009  0       0        0        0        0
bagnumber-1010 15       0        0        0        0

                         Sample size: 363
           Frequency of class labels: 36, 35, 17, 37, 37, 26, 35, 34, 36, 25, 45
                     Number of trees: 400
           Forest terminal node size: 1
       Average no. of terminal nodes: 93.6375
No. of variables tried at each split: 20
              Total no. of variables: 376
       Resampling used to grow trees: swor
    Resample size used to grow trees: 229
                            Analysis: RF-C
                              Family: class
                      Splitting rule: gini *random*
       Number of random split points: 10
                   (OOB) Brier score: 0.05189123
        (OOB) Normalized Brier score: 0.62788386
                           (OOB) AUC: 0.94833605
   (OOB) Requested performance error: 0.28099174, 0.25, 0.45714286, 0.88235294, 0.05405405, 0.05405405, 0.57692308, 0.22857143, 0.35294118, 0.13888889, 0.52, 0.11111111

Confusion matrix:

             predicted
  observed    0.015 0.015833333 0.017666667 0.017833333 0.0215 0.022 0.024
  0.015          28           1           0           0      3     1     2
  0.015833333     7          19           1           2      3     0     1
  0.017666667     5           9           2           0      1     0     0
  0.017833333     0           0           0          35      0     0     0
  0.0215          2           0           0           0     35     0     0
  0.022           2           0           0           0      0    11     9
  0.024           2           1           0           0      1     3    27
  0.025714286     0           1           0           1      0     0     0
  0.0285          0           0           0           0      0     0     1
  0.032           0           1           1           0      0     0     1
  0.033333333     0           0           0           0      0     0     0
             predicted
  observed    0.025714286 0.0285 0.032 0.033333333 class.error
  0.015                 0      1     0           0      0.2222
  0.015833333           1      0     0           1      0.4571
  0.017666667           0      0     0           0      0.8824
  0.017833333           0      0     0           2      0.0541
  0.0215                0      0     0           0      0.0541
  0.022                 0      0     0           4      0.5769
  0.024                 0      0     0           1      0.2286
  0.025714286          22      0     0          10      0.3529
  0.0285                0     31     1           3      0.1389
  0.032                 0      9    13           0      0.4800
  0.033333333           5      0     0          40      0.1111

      (OOB) Misclassification rate: 0.2754821

        all        0.015       0.015833333   0.017666667 0.017833333
ASV_200 0.02030688 0.039641610 -3.883260e-03 0.019987366  0.411415628
ASV_5   0.01927899 0.011326174  5.824890e-03 0.015989893 -0.005510031
ASV_305 0.01527574 0.022652349 -1.747467e-02 0.003997473  0.049590277
ASV_109 0.01402516 0.056630871  2.329956e-02 0.055964626  0.005510031
ASV_46  0.01076824 0.026427740  1.553304e-02 0.023984840  0.011020061
ASV_172 0.01038841 0.003775391  1.508950e-17 0.043972206  0.029386831
        0.0215      0.022        0.024       0.025714286 0.0285      0.032
ASV_200 0.001836677  0.000000000 -0.01164978 0.015989893 0.018876957 0.03533766
ASV_5   0.045916923  0.010454930  0.02135793 0.051967153 0.009438479 0.06252048
ASV_305 0.060610338  0.002613733  0.05436564 0.019987366 0.100047873 0.10329471
ASV_109 0.167137599 -0.018296128  0.03689097 0.017988630 0.018876957 0.04077423
ASV_46  0.168974276  0.026137325  0.01359141 0.007994947 0.015101566 0.01087313
ASV_172 0.101017230  0.000000000  0.07960682 0.009993683 0.003775391 0.04349251
        0.033333333  domain     phylum         class
ASV_200  0.025672662 Bacteria   Proteobacteria Gammaproteobacteria
ASV_5    0.259746930 ASV_5:core ASV_5:core     ASV_5:core
ASV_305  0.037753914 Bacteria   Proteobacteria Alphaproteobacteria
ASV_109  0.007550783 Bacteria   Proteobacteria Alphaproteobacteria
ASV_46  -0.007550783 Bacteria   Cyanobacteria  Cyanobacteriia
ASV_172  0.001510157 Bacteria   Proteobacteria Gammaproteobacteria
        order             family           genus                species
ASV_200 Thiomicrospirales Thioglobaceae    SUP05 cluster        NA
ASV_5   ASV_5:core        ASV_5:core       ASV_5:core           ASV_5:core
ASV_305 SAR11 clade       Clade III        NA                   NA
ASV_109 Rhodobacterales   Rhodobacteraceae NA                   NA
ASV_46  Synechococcales   Cyanobiaceae     Synechococcus CC9902 NA
ASV_172 Cellvibrionales   Halieaceae       OM60(NOR5) clade     NA

In [30]:
# Make one column for our outcome/response variable 

response <- as.factor(sample_data(ps_fill)$avgSST_degC)

# Combine them into 1 data frame
rf.data <- data.frame(response, predictors)
head(rf.data, n=2)


set.seed(2)
avgSST_degC.classify <- rfsrc(response~., data = rf.data, ntree = 400,
                     importance="permute", csv.num=TRUE)
avgSST_degC.classify

cbind(as.data.frame(avgSST_degC.classify$importance), as.data.frame(tax_table(ps_fill))) %>%
arrange(-all) %>%
head()

               response    ASV_479 ASV_365 ASV_535 ASV_338 ASV_930 ASV_548
bagnumber-1009 29.63623347 0       0       14      0        0      0
bagnumber-1010 29.63623347 0       7       21      0       10      0
               ASV_374 ASV_621 ASV_925 ⋯ ASV_1185 ASV_1313 ASV_1321 ASV_1399
bagnumber-1009  0      0       0       ⋯ 6        0         0       0
bagnumber-1010 12      0       0       ⋯ 8        0        12       0
               ASV_1429 ASV_1511 ASV_1546 ASV_1827 ASV_1966 ASV_2147
bagnumber-1009 0         0       0        0        0        0
bagnumber-1010 0        15       0        0        0        0

                         Sample size: 363
           Frequency of class labels: 26, 36, 35, 37, 35, 17, 30, 34, 15, 37, 25, 36
                     Number of trees: 400
           Forest terminal node size: 1
       Average no. of terminal nodes: 96.34
No. of variables tried at each split: 20
              Total no. of variables: 376
       Resampling used to grow trees: swor
    Resample size used to grow trees: 229
                            Analysis: RF-C
                              Family: class
                      Splitting rule: gini *random*
       Number of random split points: 10
                   (OOB) Brier score: 0.04886828
        (OOB) Normalized Brier score: 0.63973018
                           (OOB) AUC: 0.94813013
   (OOB) Requested performance error: 0.28650138, 0.5, 0.22222222, 0.2, 0.05405405, 0.31428571, 1, 0.1, 0.26470588, 0.86666667, 0.05405405, 0.56, 0.13888889

Confusion matrix:

             predicted
  observed    25.96821074 25.99442252 26.45430714 27.19707857 27.43930579
  25.96821074          13           2          10           0           0
  25.99442252           1          28           1           0           0
  26.45430714           4           2          28           0           0
  27.19707857           0           0           0          35           1
  27.43930579           1           4           0           3          24
  27.62378409           0           4           0           0          12
  29.0513381            0           0           0           0           0
  29.12767665           0           1           0           0           1
  29.41867975           0           0           0           0           0
  29.49291322           0           1           0           0           1
  29.63623347           0           0           1           2           0
  30.03815238           0           0           1           0           0
             predicted
  observed    27.62378409 29.0513381 29.12767665 29.41867975 29.49291322
  25.96821074           0          0           1           0           0
  25.99442252           0          0           1           0           4
  26.45430714           0          0           0           0           1
  27.19707857           0          0           1           0           0
  27.43930579           0          0           2           0           1
  27.62378409           0          0           0           0           1
  29.0513381            0         27           3           0           0
  29.12767665           0          7          25           0           0
  29.41867975           0          2          11           2           0
  29.49291322           0          0           0           0          35
  29.63623347           1          0           0           0           0
  30.03815238           0          1           1           0           0
             predicted
  observed    29.63623347 30.03815238 class.error
  25.96821074           0           0      0.5000
  25.99442252           0           1      0.2222
  26.45430714           0           0      0.2000
  27.19707857           0           0      0.0541
  27.43930579           0           0      0.3143
  27.62378409           0           0      1.0000
  29.0513381            0           0      0.1000
  29.12767665           0           0      0.2647
  29.41867975           0           0      0.8667
  29.49291322           0           0      0.0541
  29.63623347          11          10      0.5600
  30.03815238           2          31      0.1389

      (OOB) Misclassification rate: 0.2865014

        all        25.96821074  25.99442252  26.45430714 27.19707857
ASV_200 0.01382010  0.005227465  0.026427740 -0.02912445 0.308561721
ASV_46  0.01298713  0.044433453  0.009438479  0.02912445 0.022040123
ASV_109 0.01240505  0.010454930  0.047192393  0.06213216 0.009183385
ASV_94  0.01223200  0.036592255 -0.003775391  0.06989868 0.014693415
ASV_5   0.01180658 -0.013068663  0.026427740  0.01553304 0.007346708
ASV_172 0.01150678  0.020909860  0.020764653  0.11261453 0.009183385
        27.43930579 27.62378409  29.0513381  29.12767665  29.41867975
ASV_200 -0.00194163  0.003997473 0.038508993 -0.001998737  1.359141e-02
ASV_46   0.04854075 -0.007994947 0.013591409  0.009993683  7.544748e-18
ASV_109  0.02718282  0.000000000 0.029448053  0.007994947 -9.060939e-03
ASV_94   0.06407379  0.031979786 0.006795705  0.023984840 -1.812188e-02
ASV_5    0.03106608  0.011992420 0.210666842  0.013991156  5.436564e-02
ASV_172  0.00582489  0.035977259 0.031713288  0.005996210  6.342658e-02
        29.49291322 29.63623347  30.03815238  domain     phylum
ASV_200 0.01836677   0.002718282 -0.001887696 Bacteria   Proteobacteria
ASV_46  0.17448431   0.002718282  0.013213870 Bacteria   Cyanobacteria
ASV_109 0.14693415   0.000000000  0.005663087 Bacteria   Proteobacteria
ASV_94  0.11571065   0.032619382 -0.015101566 Bacteria   Bacteroidota
ASV_5   0.02204012   0.027182818 -0.009438479 ASV_5:core ASV_5:core
ASV_172 0.09183385  -0.005436564 -0.015101566 Bacteria   Proteobacteria
        class               order             family
ASV_200 Gammaproteobacteria Thiomicrospirales Thioglobaceae
ASV_46  Cyanobacteriia      Synechococcales   Cyanobiaceae
ASV_109 Alphaproteobacteria Rhodobacterales   Rhodobacteraceae
ASV_94  Bacteroidia         NA                NA
ASV_5   ASV_5:core          ASV_5:core        ASV_5:core
ASV_172 Gammaproteobacteria Cellvibrionales   Halieaceae
        genus                species
ASV_200 SUP05 cluster        NA
ASV_46  Synechococcus CC9902 NA
ASV_109 NA                   NA
ASV_94  NA                   NA
ASV_5   ASV_5:core           ASV_5:core
ASV_172 OM60(NOR5) clade     NA

In [33]:
# Make one column for our outcome/response variable 

response <- as.factor(sample_data(ps_fill)$Speed.cm.s)

# Combine them into 1 data frame
rf.data <- data.frame(response, predictors)
head(rf.data, n=2)


set.seed(2)
Speed.cm.s.classify <- rfsrc(response~., data = rf.data, ntree = 400,
                     importance="permute", csv.num=TRUE)
Speed.cm.s.classify

cbind(as.data.frame(Speed.cm.s.classify$importance), as.data.frame(tax_table(ps_fill))) %>%
arrange(-all) %>%
head()

               response    ASV_479 ASV_365 ASV_535 ASV_338 ASV_930 ASV_548
bagnumber-1009 4.852118056 0       0       14      0        0      0
bagnumber-1010 4.852118056 0       7       21      0       10      0
               ASV_374 ASV_621 ASV_925 ⋯ ASV_1185 ASV_1313 ASV_1321 ASV_1399
bagnumber-1009  0      0       0       ⋯ 6        0         0       0
bagnumber-1010 12      0       0       ⋯ 8        0        12       0
               ASV_1429 ASV_1511 ASV_1546 ASV_1827 ASV_1966 ASV_2147
bagnumber-1009 0         0       0        0        0        0
bagnumber-1010 0        15       0        0        0        0

                         Sample size: 363
           Frequency of class labels: 26, 35, 45, 25, 37, 36, 36, 34, 54, 35
                     Number of trees: 400
           Forest terminal node size: 1
       Average no. of terminal nodes: 92.2725
No. of variables tried at each split: 20
              Total no. of variables: 376
       Resampling used to grow trees: swor
    Resample size used to grow trees: 229
                            Analysis: RF-C
                              Family: class
                      Splitting rule: gini *random*
       Number of random split points: 10
                   (OOB) Brier score: 0.0566031
        (OOB) Normalized Brier score: 0.62892331
                           (OOB) AUC: 0.95147709
   (OOB) Requested performance error: 0.27823691, 0.57692308, 0.14285714, 0.08888889, 0.4, 0.08108108, 0.27777778, 0.13888889, 0.41176471, 0.31481481, 0.51428571

Confusion matrix:

             predicted
  observed    4.306533713 4.388159722 4.795925926 4.852118056 5.229809028
  4.306533713          11          10           3           0           0
  4.388159722           1          30           1           0           1
  4.795925926           0           0          41           0           0
  4.852118056           0           1           1          15           0
  5.229809028           0           0           0           0          34
  5.33154908            1           3           0           0           2
  5.542543403           0           1           3           1           0
  5.699322917           0           0          11           0           0
  6.026627907           0           0           1           0           1
  6.636767068           1           1           0           0           2
             predicted
  observed    5.33154908 5.542543403 5.699322917 6.026627907 6.636767068
  4.306533713          1           0           0           0           1
  4.388159722          2           0           0           0           0
  4.795925926          0           0           4           0           0
  4.852118056          0           6           0           2           0
  5.229809028          2           0           0           1           0
  5.33154908          26           1           1           1           1
  5.542543403          0          31           0           0           0
  5.699322917          0           0          20           2           1
  6.026627907          4           0           0          38          10
  6.636767068          2           0           2          10          17
             predicted
  observed    class.error
  4.306533713      0.5769
  4.388159722      0.1429
  4.795925926      0.0889
  4.852118056      0.4000
  5.229809028      0.0811
  5.33154908       0.2778
  5.542543403      0.1389
  5.699322917      0.4118
  6.026627907      0.2963
  6.636767068      0.5143

      (OOB) Misclassification rate: 0.2754821

         all        4.306533713 4.388159722 4.795925926 4.852118056
ASV_5    0.01766093 0.015682395 0.02329956   0.26427740  0.029901100
ASV_200  0.01646681 0.028751058 0.02135793   0.03322344  0.021746255
ASV_109  0.01410470 0.007841198 0.07766520   0.03624376  0.008154845
ASV_305  0.01351412 0.018296128 0.04465749   0.01661172  0.081548455
ASV_1827 0.01144084 0.005227465 0.01553304   0.01359141 -0.013591409
ASV_68   0.01050936 0.013068663 0.01747467  -0.01359141  0.013591409
         5.229809028 5.33154908  5.542543403  5.699322917  6.026627907
ASV_5    0.01285674  0.037753914  0.013213870  0.005996210 0.002516928
ASV_200  0.02020345  0.037753914 -0.003775391  0.017988630 0.193803427
ASV_109  0.13224074  0.058518567  0.032090827 -0.009993683 0.025169276
ASV_305  0.02571348  0.030203131  0.094384786  0.025983576 0.039012378
ASV_1827 0.02387680  0.005663087  0.218972703  0.009993683 0.010067710
ASV_68   0.06979372  0.020764653  0.011326174  0.087944412 0.010067710
         6.636767068  domain     phylum         class
ASV_5     0.019416299 ASV_5:core ASV_5:core     ASV_5:core
ASV_200  -0.015533039 Bacteria   Proteobacteria Gammaproteobacteria
ASV_109  -0.005824890 Bacteria   Proteobacteria Alphaproteobacteria
ASV_305  -0.001941630 Bacteria   Proteobacteria Alphaproteobacteria
ASV_1827  0.009708149 Bacteria   Bacteroidota   Rhodothermia
ASV_68    0.066015416 NA         NA             NA
         order             family           genus         species
ASV_5    ASV_5:core        ASV_5:core       ASV_5:core    ASV_5:core
ASV_200  Thiomicrospirales Thioglobaceae    SUP05 cluster NA
ASV_109  Rhodobacterales   Rhodobacteraceae NA            NA
ASV_305  SAR11 clade       Clade III        NA            NA
ASV_1827 Balneolales       Balneolaceae     Balneola      NA
ASV_68   NA                NA               NA            NA

In [35]:
# Make one column for our outcome/response variable 

response <- as.factor(sample_data(ps_fill)$avgchla_mgm.3)

# Combine them into 1 data frame
rf.data <- data.frame(response, predictors)
head(rf.data, n=2)


set.seed(2)
avgchla_mgm.3.classify <- rfsrc(response~., data = rf.data, ntree = 400,
                     importance="permute", csv.num=TRUE)
avgchla_mgm.3.classify

cbind(as.data.frame(avgchla_mgm.3.classify$importance), as.data.frame(tax_table(ps_fill))) %>%
arrange(-all) %>%
head()

               response    ASV_479 ASV_365 ASV_535 ASV_338 ASV_930 ASV_548
bagnumber-1009 1.792091669 0       0       14      0        0      0
bagnumber-1010 1.792091669 0       7       21      0       10      0
               ASV_374 ASV_621 ASV_925 ⋯ ASV_1185 ASV_1313 ASV_1321 ASV_1399
bagnumber-1009  0      0       0       ⋯ 6        0         0       0
bagnumber-1010 12      0       0       ⋯ 8        0        12       0
               ASV_1429 ASV_1511 ASV_1546 ASV_1827 ASV_1966 ASV_2147
bagnumber-1009 0         0       0        0        0        0
bagnumber-1010 0        15       0        0        0        0

                         Sample size: 363
           Frequency of class labels: 36, 35, 26, 34, 17, 15, 37, 25, 30, 35, 36, 37
                     Number of trees: 400
           Forest terminal node size: 1
       Average no. of terminal nodes: 96.34
No. of variables tried at each split: 20
              Total no. of variables: 376
       Resampling used to grow trees: swor
    Resample size used to grow trees: 229
                            Analysis: RF-C
                              Family: class
                      Splitting rule: gini *random*
       Number of random split points: 10
                   (OOB) Brier score: 0.04886828
        (OOB) Normalized Brier score: 0.63973018
                           (OOB) AUC: 0.94813013
   (OOB) Requested performance error: 0.28650138, 0.22222222, 0.31428571, 0.5, 0.26470588, 1, 0.86666667, 0.05405405, 0.56, 0.1, 0.2, 0.13888889, 0.05405405

Confusion matrix:

             predicted
  observed    0.39995314 0.518854953 0.696025807 0.838890013 0.98994618
  0.39995314          28           0           1           1          0
  0.518854953          4          24           1           2          0
  0.696025807          2           0          13           1          0
  0.838890013          1           1           0          25          0
  0.98994618           4          12           0           0          0
  1.193063102          0           0           0          10          0
  1.507777124          1           1           0           0          0
  1.792091669          0           0           0           0          1
  1.997572561          0           0           0           3          0
  2.700257501          2           0           4           0          0
  3.090697605          0           0           0           0          0
  3.242377305          0           1           0           1          0
             predicted
  observed    1.193063102 1.507777124 1.792091669 1.997572561 2.700257501
  0.39995314            0           4           0           0           1
  0.518854953           0           1           0           0           0
  0.696025807           0           0           0           0          10
  0.838890013           1           0           0           6           0
  0.98994618            0           1           0           0           0
  1.193063102           2           0           0           3           0
  1.507777124           0          35           0           0           0
  1.792091669           0           0          11           0           1
  1.997572561           0           0           0          27           0
  2.700257501           0           1           0           0          28
  3.090697605           0           0           2           2           1
  3.242377305           0           0           0           0           0
             predicted
  observed    3.090697605 3.242377305 class.error
  0.39995314            1           0      0.2222
  0.518854953           0           3      0.3143
  0.696025807           0           0      0.5000
  0.838890013           0           0      0.2647
  0.98994618            0           0      1.0000
  1.193063102           0           0      0.8667
  1.507777124           0           0      0.0541
  1.792091669          10           2      0.5600
  1.997572561           0           0      0.1000
  2.700257501           0           0      0.2000
  3.090697605          31           0      0.1389
  3.242377305           0          35      0.0541

      (OOB) Misclassification rate: 0.2865014

        all        0.39995314   0.518854953 0.696025807  0.838890013
ASV_200 0.01604582  0.026427740 -0.00388326  0.002613733 -0.001998737
ASV_109 0.01534511  0.043417001  0.03494934  0.007841198  0.005996210
ASV_94  0.01396841 -0.007550783  0.06795705  0.026137325  0.027982313
ASV_46  0.01333821  0.016989261  0.05436564  0.047047185  0.009993683
ASV_5   0.01249923  0.026427740  0.03106608 -0.015682395  0.037975996
ASV_172 0.01150162  0.020764653  0.02329956  0.026137325  0.011992420
        0.98994618   1.193063102  1.507777124 1.792091669  1.997572561
ASV_200  0.019987366  0.018121879 0.03489686   0.019027973 0.05210040
ASV_109 -0.003997473 -0.013591409 0.20019778   0.002718282 0.02265235
ASV_94   0.047969679 -0.013591409 0.13591409   0.048929073 0.02038711
ASV_46   0.015989893 -0.009060939 0.18734104   0.005436564 0.02718282
ASV_5    0.007994947  0.031713288 0.03306018   0.013591409 0.21519731
ASV_172  0.035977259  0.045304697 0.14142412  -0.005436564 0.01585664
        2.700257501 3.090697605   3.242377305  domain     phylum
ASV_200 -0.01553304  1.510157e-02  0.293868306 Bacteria   Proteobacteria
ASV_109  0.06213216  1.132617e-02  0.034896861 Bacteria   Proteobacteria
ASV_94   0.05436564 -1.887696e-03  0.014693415 Bacteria   Bacteroidota
ASV_46   0.00776652  1.132617e-02  0.005510031 Bacteria   Cyanobacteria
ASV_5    0.00582489  7.544748e-18  0.011020061 ASV_5:core ASV_5:core
ASV_172  0.06601542 -9.438479e-03 -0.007346708 Bacteria   Proteobacteria
        class               order             family
ASV_200 Gammaproteobacteria Thiomicrospirales Thioglobaceae
ASV_109 Alphaproteobacteria Rhodobacterales   Rhodobacteraceae
ASV_94  Bacteroidia         NA                NA
ASV_46  Cyanobacteriia      Synechococcales   Cyanobiaceae
ASV_5   ASV_5:core          ASV_5:core        ASV_5:core
ASV_172 Gammaproteobacteria Cellvibrionales   Halieaceae
        genus                species
ASV_200 SUP05 cluster        NA
ASV_109 NA                   NA
ASV_94  NA                   NA
ASV_46  Synechococcus CC9902 NA
ASV_5   ASV_5:core           ASV_5:core
ASV_172 OM60(NOR5) clade     NA

In [39]:
colnames(sample_data(ps_fill))

 [1] "collection_date"       "Speed.cm.s."           "Bearing.degrees."
 [4] "Velocity.N.cm.s."      "Velocity.E.cm.s."      "Temperature.C."
 [7] "reef"                  "Genotype"              "Fragment_number"
[10] "Month"                 "Year"                  "Fragment_num"
[13] "day"                   "Survey."               "LiveFrag"
[16] "L"                     "W"                     "H"
[19] "Adjusted.Area"         "S01FragCount"          "Year.x"
[22] "Si.uM."                "NO2.uM."               "N.N.uM."
[25] "NO3.uM."               "PO4.uM."               "sample_ID"
[28] "sample_ID2"            "Health"                "Month.x"
[31] "Samp_trip"             "joining_info"          "order"
[34] "species"               "time_Reef"             "Cluster"
[37] "sampling_trip"         "X"                     "colour_reef"
[40] "colour_genotype"       "colour_reef_genotype"  "colour_timepoint"
[43] "colour_timepoint_reef" "cluster_latitude"      "cluster_longitude"
[46] "cluster_depth"         "Year.y"                "Month.y"
[49] "Lat_decimal"           "Long_decimal"          "avgchla_mgm.3"
[52] "sdchla_mgm.3"          "avgSST_degC"           "sdSST_degC"

In [41]:


# Make one column for our outcome/response variable 

response <- as.factor(sample_data(ps_fill)$Si.uM.)

# Combine them into 1 data frame
rf.data <- data.frame(response, predictors)
head(rf.data, n=2)


set.seed(2)
Si.uM.classify <- rfsrc(response~., data = rf.data, ntree = 400,
                     importance="permute", csv.num=TRUE)
Si.uM.classify

cbind(as.data.frame(Si.uM.classify$importance), as.data.frame(tax_table(ps_fill))) %>%
arrange(-all) %>%
head()

               response ASV_479 ASV_365 ASV_535 ASV_338 ASV_930 ASV_548 ASV_374
bagnumber-1009 0.706    0       0       14      0        0      0        0
bagnumber-1010 0.706    0       7       21      0       10      0       12
               ASV_621 ASV_925 ⋯ ASV_1185 ASV_1313 ASV_1321 ASV_1399 ASV_1429
bagnumber-1009 0       0       ⋯ 6        0         0       0        0
bagnumber-1010 0       0       ⋯ 8        0        12       0        0
               ASV_1511 ASV_1546 ASV_1827 ASV_1966 ASV_2147
bagnumber-1009  0       0        0        0        0
bagnumber-1010 15       0        0        0        0

                         Sample size: 363
           Frequency of class labels: 30, 15, 37, 34, 35, 26, 17, 36, 37, 36, 25, 35
                     Number of trees: 400
           Forest terminal node size: 1
       Average no. of terminal nodes: 96.34
No. of variables tried at each split: 20
              Total no. of variables: 376
       Resampling used to grow trees: swor
    Resample size used to grow trees: 229
                            Analysis: RF-C
                              Family: class
                      Splitting rule: gini *random*
       Number of random split points: 10
                   (OOB) Brier score: 0.04886828
        (OOB) Normalized Brier score: 0.63973018
                           (OOB) AUC: 0.94813013
   (OOB) Requested performance error: 0.27823691, 0.1, 0.86666667, 0.05405405, 0.26470588, 0.2, 0.5, 1, 0.22222222, 0.05405405, 0.13888889, 0.56, 0.22857143

Confusion matrix:

             predicted
  observed    0.033333333 0.066666667 0.159166667 0.2 0.308 0.335 0.426166667
  0.033333333          27           0           0   3     0     0           0
  0.066666667           2           2           0  10     0     1           0
  0.159166667           0           0          35   1     0     0           0
  0.2                   7           0           0  25     0     0           0
  0.308                 0           0           0   0    28     4           0
  0.335                 0           0           0   1    10    13           0
  0.426166667           0           0           0   0     0     0           0
  0.504                 0           0           0   1     1     1           0
  0.5265                0           0           0   0     0     0           0
  0.613                 1           0           0   1     1     0           0
  0.706                 0           0           2   0     1     0           1
  1.904166667           0           0           3   2     0     1           0
             predicted
  observed    0.504 0.5265 0.613 0.706 1.904166667 class.error
  0.033333333     0      0     0     0           0      0.1000
  0.066666667     0      0     0     0           0      0.8667
  0.159166667     0      0     0     0           1      0.0541
  0.2             1      0     0     0           1      0.2647
  0.308           2      1     0     0           0      0.2000
  0.335           2      0     0     0           0      0.5000
  0.426166667     4      1     0     0          12      1.0000
  0.504          28      4     1     0           0      0.2222
  0.5265          1     35     0     0           1      0.0541
  0.613           0      0    31     2           0      0.1389
  0.706           0      0    10    11           0      0.5600
  1.904166667     4      2     0     0          23      0.3429

      (OOB) Misclassification rate: 0.2892562

        all        0.033333333  0.066666667  0.159166667 0.2
ASV_200 0.01675871  0.040774227  0.009060939 0.32325514  -0.007994947
ASV_46  0.01293011  0.013591409  0.009060939 0.02755015   0.009993683
ASV_172 0.01234268  0.020387114  0.031713288 0.01469342   0.021986103
ASV_109 0.01185759  0.009060939 -0.027182818 0.03122351   0.009993683
ASV_94  0.01153184  0.004530470 -0.013591409 0.01836677   0.027982313
ASV_305 0.01095200 -0.018121879  0.004530470 0.05142695   0.011992420
        0.308       0.335       0.426166667 0.504       0.5265     0.613
ASV_200 -0.01941630 0.005227465 0.019987366  0.02831544 0.03489686  0.015101566
ASV_46   0.02912445 0.052274651 0.007994947  0.01132617 0.15979089  0.022652349
ASV_172  0.09319823 0.028751058 0.011992420  0.02454004 0.08816049  0.007550783
ASV_109  0.06213216 0.033978523 0.000000000  0.03964161 0.15795421 -0.003775391
ASV_94   0.05824890 0.067957046 0.023984840 -0.01698926 0.10101723  0.007550783
ASV_305  0.03300771 0.020909860 0.003997473  0.02076465 0.06428369  0.090609394
        0.706        1.904166667 domain   phylum         class
ASV_200  0.013591409  0.00776652 Bacteria Proteobacteria Gammaproteobacteria
ASV_46   0.013591409  0.01941630 Bacteria Cyanobacteria  Cyanobacteriia
ASV_172 -0.002718282  0.03106608 Bacteria Proteobacteria Gammaproteobacteria
ASV_109  0.038055946 -0.02718282 Bacteria Proteobacteria Alphaproteobacteria
ASV_94   0.043492509  0.02718282 Bacteria Bacteroidota   Bacteroidia
ASV_305  0.054365637 -0.01941630 Bacteria Proteobacteria Alphaproteobacteria
        order             family           genus                species
ASV_200 Thiomicrospirales Thioglobaceae    SUP05 cluster        NA
ASV_46  Synechococcales   Cyanobiaceae     Synechococcus CC9902 NA
ASV_172 Cellvibrionales   Halieaceae       OM60(NOR5) clade     NA
ASV_109 Rhodobacterales   Rhodobacteraceae NA                   NA
ASV_94  NA                NA               NA                   NA
ASV_305 SAR11 clade       Clade III        NA                   NA

In [44]:
# Make one column for our outcome/response variable 

response <- as.factor(sample_data(ps_fill)$PO4.uM.)

# Combine them into 1 data frame
rf.data <- data.frame(response, predictors)
head(rf.data, n=2)


set.seed(2)
PO4.uM.classify <- rfsrc(response~., data = rf.data, ntree = 400,
                     importance="permute", csv.num=TRUE)
PO4.uM.classify

cbind(as.data.frame(PO4.uM.classify$importance), as.data.frame(tax_table(ps_fill))) %>%
arrange(-all) %>%
head()

               response ASV_479 ASV_365 ASV_535 ASV_338 ASV_930 ASV_548 ASV_374
bagnumber-1009 0.0685   0       0       14      0        0      0        0
bagnumber-1010 0.0685   0       7       21      0       10      0       12
               ASV_621 ASV_925 ⋯ ASV_1185 ASV_1313 ASV_1321 ASV_1399 ASV_1429
bagnumber-1009 0       0       ⋯ 6        0         0       0        0
bagnumber-1010 0       0       ⋯ 8        0        12       0        0
               ASV_1511 ASV_1546 ASV_1827 ASV_1966 ASV_2147
bagnumber-1009  0       0        0        0        0
bagnumber-1010 15       0        0        0        0

                         Sample size: 363
           Frequency of class labels: 37, 37, 36, 26, 36, 15, 30, 17, 35, 25, 35, 34
                     Number of trees: 400
           Forest terminal node size: 1
       Average no. of terminal nodes: 96.34
No. of variables tried at each split: 20
              Total no. of variables: 376
       Resampling used to grow trees: swor
    Resample size used to grow trees: 229
                            Analysis: RF-C
                              Family: class
                      Splitting rule: gini *random*
       Number of random split points: 10
                   (OOB) Brier score: 0.04886828
        (OOB) Normalized Brier score: 0.63973018
                           (OOB) AUC: 0.94813013
   (OOB) Requested performance error: 0.28374656, 0.05405405, 0.05405405, 0.22222222, 0.5, 0.13888889, 0.86666667, 0.1, 1, 0.2, 0.56, 0.28571429, 0.26470588

Confusion matrix:

             predicted
  observed    0.023 0.029666667 0.037 0.039 0.044 0.046666667 0.05 0.055 0.056
  0.023          35           0     1     0     0           0    0     0     0
  0.029666667     0          35     0     0     0           0    0     0     0
  0.037           4           0    28     1     1           0    0     0     1
  0.039           0           0     2    13     0           0    0     0    10
  0.044           0           0     0     0    31           0    1     0     1
  0.046666667     0           0     0     0     0           2    2     0     0
  0.05            0           0     0     0     0           0   27     0     0
  0.055           1           0     4     0     0           0    0     0     0
  0.056           1           0     2     4     0           0    0     0    28
  0.0685          0           2     0     0    10           0    0     1     1
  0.074833333     2           3     4     1     0           0    0     0     0
  0.082857143     0           0     1     0     0           1    6     0     0
             predicted
  observed    0.0685 0.074833333 0.082857143 class.error
  0.023            0           1           0      0.0541
  0.029666667      0           1           1      0.0541
  0.037            0           0           1      0.2222
  0.039            0           0           1      0.5000
  0.044            2           0           1      0.1389
  0.046666667      0           0          11      0.8667
  0.05             0           0           3      0.1000
  0.055            0          12           0      1.0000
  0.056            0           0           0      0.2000
  0.0685          11           0           0      0.5600
  0.074833333      0          23           2      0.3429
  0.082857143      0           1          25      0.2647

      (OOB) Misclassification rate: 0.2892562

        all        0.023      0.029666667 0.037        0.039       0.044
ASV_200 0.01584853 0.03489686 0.317745106  0.020764653 0.002613733  0.011326174
ASV_172 0.01423087 0.12489403 0.009183385  0.022652349 0.026137325  0.015101566
ASV_46  0.01223113 0.14326080 0.023876800  0.007550783 0.047047185  0.024540044
ASV_109 0.01214137 0.13958745 0.022040123  0.052855480 0.007841198  0.009438479
ASV_305 0.01151788 0.04224357 0.053263630  0.016989261 0.005227465  0.122700221
ASV_94  0.01146006 0.09550720 0.014693415 -0.005663087 0.044433453 -0.005663087
        0.046666667 0.05         0.055        0.056       0.0685
ASV_200  0.00453047  0.047569932 -0.003997473 -0.02912445 0.01359141
ASV_172  0.04530470  0.029448053  0.047969679  0.08931497 0.01087313
ASV_46  -0.00453047  0.013591409 -0.019987366  0.03106608 0.01359141
ASV_109 -0.02265235  0.015856644  0.003997473  0.06601542 0.03533766
ASV_305  0.00000000 -0.004530470 -0.015989893  0.03689097 0.05980220
ASV_94  -0.02265235 -0.006795705  0.019987366  0.06407379 0.05708392
        0.074833333  0.082857143 domain   phylum         class
ASV_200  0.009708149 0.001998737 Bacteria Proteobacteria Gammaproteobacteria
ASV_172  0.021357929 0.009993683 Bacteria Proteobacteria Gammaproteobacteria
ASV_46   0.038832598 0.015989893 Bacteria Cyanobacteria  Cyanobacteriia
ASV_109 -0.017474669 0.017988630 Bacteria Proteobacteria Alphaproteobacteria
ASV_305 -0.007766520 0.011992420 Bacteria Proteobacteria Alphaproteobacteria
ASV_94   0.036890968 0.045970943 Bacteria Bacteroidota   Bacteroidia
        order             family           genus                species
ASV_200 Thiomicrospirales Thioglobaceae    SUP05 cluster        NA
ASV_172 Cellvibrionales   Halieaceae       OM60(NOR5) clade     NA
ASV_46  Synechococcales   Cyanobiaceae     Synechococcus CC9902 NA
ASV_109 Rhodobacterales   Rhodobacteraceae NA                   NA
ASV_305 SAR11 clade       Clade III        NA                   NA
ASV_94  NA                NA               NA                   NA